### PR TITLE
Changed newfavicon to favicon (issue #91)

### PR DESCRIPTION
**Pull request by colopop**

### CODE REVIEW

**Comment by luciencd** [comment]
Wasn't the favicon before a dollar sign? What changed since then?

**Comment by colopop** [comment]
Just changed the filename, since Kevin raised it as a best practices kind of issue

**Comment by reitakCS** [comment]
There seems to be an issue locally for me, the local file is the dollar sign icon, but I'm seeing the Angular one in my browser, for both firefox and chrome, however when I inspect the element its and open the image file in a new tab I'm seeing the dollar sign again

**Comment by reitakCS** [comment]
Nvm, clearing cache fixed both, I see the new things now, everything is in order

**Pull request merged**
